-- MySQL Script generated by MySQL Workbench
-- Sun Feb 19 08:35:50 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema lineauthdb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema lineauthdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `lineauthdb` DEFAULT CHARACTER SET utf8 ;
USE `lineauthdb` ;

-- -----------------------------------------------------
-- Table `lineauthdb`.`Users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lineauthdb`.`Users` ;

CREATE TABLE IF NOT EXISTS `lineauthdb`.`Users` (
  `user_id` VARCHAR(64) NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `name` VARCHAR(64) NULL,
  `email` VARCHAR(256) NULL,
  `password` VARCHAR(512) NULL,
  `status` INT NULL,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lineauthdb`.`SnsId`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lineauthdb`.`SnsId` ;

CREATE TABLE IF NOT EXISTS `lineauthdb`.`SnsId` (
  `user_id` VARCHAR(64) NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `sns_id` VARCHAR(64) NOT NULL,
  INDEX `user_id_idx` (`user_id` ASC) VISIBLE,
  PRIMARY KEY (`sns_id`),
  CONSTRAINT `SnsId.user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `lineauthdb`.`Users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
